---
title: "Summarize the HTSeq-count result files"
author: "Author: Vegetable Bird"
date: "`r format(Sys.time(), '%F')`"
output:
  html_document:
    df_print: paged
---

# Usage introduction

```{r warning=F, message=F}
rm(list = ls())
ptm <- proc.time()
# proc.time() - ptm
options(stringsAsFactors = F)
library("magrittr")
library("R.utils")
library("readxl")
library("ggplot2")
library("ggpubr")
library("edgeR")
```

# Set up input and output files and directories.

```{r}
grouping_path <- file.path("..", "01_cloud_workflow", "metadata", "samples_cell_lines_batch_both_SampleGroup.xlsx")
expression_path <- file.path(".", "intermediate_files", "gene_expression_matrix.raw_count.csv.bz2")

output_directory <- file.path(".", "intermediate_files")
output_graph_base_name <- "batch_effect_test"
```

# Read the files from hard disk.

```{r}
raw_expression_dataframe <- read.csv(expression_path, row.names = 1, check.names = F)
grouping_dataframe <- read_excel(grouping_path)

normalized_expression_dataframe <- cpm(raw_expression_dataframe, log = T, prior.count = 0.01) %>%
    as.data.frame
```


# Calculate the total read counts for each column (sample).

```{r}
get_long_dataframe <- function(an_expression_dataframe, factor_dataframe, statistical_function) {
    
    # an_expression_dataframe<- raw_expression_dataframe
    # factor_dataframe <- grouping_dataframe
    # statistical_function <- sum
    batch_1_column_names <- factor_dataframe %$%
        subset(., Batch == 1) %>%
        use_series(., File)
    batch_2_column_names <- factor_dataframe %$%
        subset(., Batch == 2) %>%
        use_series(., File)

    batch_1_dataframe <- an_expression_dataframe %$%
        .[, colnames(.) %in% batch_1_column_names]
    batch_2_dataframe <- an_expression_dataframe %$%
        .[, colnames(.) %in% batch_2_column_names]

    batch_1_read_statistics <- apply(batch_1_dataframe, 2, statistical_function)
    batch_2_read_statistics <- apply(batch_2_dataframe, 2, statistical_function)

    # Probably not all normal distribution.
    shapiro.test(batch_1_read_statistics)
    shapiro.test(batch_2_read_statistics)

    # Some statistics test.
    var.test(batch_1_read_statistics, batch_2_read_statistics)
    wilcox.test(batch_1_read_statistics, batch_2_read_statistics)
    
    dataframe_to_plot <- data.frame(
        statistic_value = c(batch_1_read_statistics, batch_2_read_statistics),
        batch_group = c(rep("batch_1", times = length(batch_1_read_statistics)),
                        rep("batch_2", times = length(batch_2_read_statistics)))
    )
}

raw_long_dataframe <- get_long_dataframe(raw_expression_dataframe, grouping_dataframe, sum)
raw_long_dataframe

normalized_long_dataframe <- get_long_dataframe(normalized_expression_dataframe, grouping_dataframe, median)
normalized_long_dataframe
```

# Plot a graph to see the batch affect.

```{r}
plot_dataframe_list <- list(raw_count_colsums = raw_long_dataframe, log2_cpm_medians = normalized_long_dataframe)
my_comparisons <- list(c("batch_1", "batch_2"))

for (i in names(plot_dataframe_list)) {
    my_plot <- ggplot(plot_dataframe_list[[i]], aes(x = batch_group, y = statistic_value, color = batch_group)) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(width = 0.25) +
        stat_compare_means(comparisons = my_comparisons, method = "wilcox.test") +
        ggtitle("Wilcoxon_rank_sum_test") +
        ylab(i)
    
    ggsave(filename = paste(output_graph_base_name, i, "pdf", sep = "."),
           plot = my_plot,
           device = "pdf",
           path = output_directory,
           width = 170,
           height = 170,
           units = "mm")

my_plot
}
```

```{r}
proc.time() - ptm
```

