---
title: "Analyzing RNA-seq data with DESeq2"
author: "Author: Old Vegetable Bird"
date: "`r format(Sys.time(), '%F')`"
output:
    rmarkdown::html_document:
        theme: readable
        highlight: textmate
        df_print: paged
---

# Introduction

[DESeq2 official tutorial](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)

[DESeq2 result explanation](https://chipster.csc.fi/manual/deseq2.html)

[The Wald test is a standard way to extract a P value from a regression fit](https://www.biostars.org/p/308142/)

Two batches can be the multi-factor designs besides the treated vs untreated.
Two batches should be seeing no difference in expression


#chunk 1: set up global environment and load packages 
```{r message = F, warning = F}
rm(list = ls())
ptm <- proc.time()
# proc.time() - ptm
options(stringsAsFactors = F)
library("magrittr")
library("DESeq2")
library("readxl")
```


# Set up input and output files and directories.

```{r}
grouping_path <- file.path("..", "01_cloud_workflow", "metadata", "samples_cell_lines_batch_both_SampleGroup.xlsx")
expression_path <- file.path(".", "intermediate_files", "htseq_count_expression_matrix.csv.bz2")

output_directory <- file.path(".", "intermediate_files")
```

# Read the files from hard disk.

```{r}
raw_expression_dataframe <- read.csv(expression_path, row.names = 1, check.names = F)
grouping_dataframe <- read_excel(grouping_path)
```


```{r}
dds <- DESeqDataSetFromMatrix(countData = raw_expression_dataframe,
                              colData = grouping_dataframe,
                              design = ~Group)
dds
```

```{r}
proc.time() - ptm
```

